# Default costs for each colour in the shop.
colour_costs:
  black: 100000
  dark_blue: 5000
  dark_green: 5000
  dark_aqua: 5000
  dark_red: 5000
  dark_purple: 5000
  gold: 5000
  gray: 500
  dark_gray: 750
  blue: 3000
  green: 3000
  aqua: 7500
  light_purple: 10000
  yellow: 1000
  white: 0

heart_cost: 5

# Costs for purchasing custom MOTD messages with different durations
motd_costs:
  day: 100
  week: 500
  month: 1500
